"""empty message

Revision ID: f487e41e886d
Revises: 630075e5829e
Create Date: 2021-08-04 08:42:27.164735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f487e41e886d'
down_revision = '630075e5829e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_anime', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('table_anime', sa.Column('userId', sa.Integer(), nullable=True))
    op.add_column('table_anime', sa.Column('animeId', sa.Integer(), nullable=True))
    op.drop_constraint('table_anime_user_id_fkey', 'table_anime', type_='foreignkey')
    op.drop_constraint('table_anime_anime_id_fkey', 'table_anime', type_='foreignkey')
    op.create_foreign_key(None, 'table_anime', 'users', ['userId'], ['id'])
    op.create_foreign_key(None, 'table_anime', 'anime', ['animeId'], ['id'])
    op.drop_column('table_anime', 'user_id')
    op.drop_column('table_anime', 'anime_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_anime', sa.Column('anime_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('table_anime', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'table_anime', type_='foreignkey')
    op.drop_constraint(None, 'table_anime', type_='foreignkey')
    op.create_foreign_key('table_anime_anime_id_fkey', 'table_anime', 'anime', ['anime_id'], ['id'])
    op.create_foreign_key('table_anime_user_id_fkey', 'table_anime', 'users', ['user_id'], ['id'])
    op.drop_column('table_anime', 'animeId')
    op.drop_column('table_anime', 'userId')
    op.drop_column('table_anime', 'id')
    # ### end Alembic commands ###
