"""empty message

Revision ID: 151c1ec2e162
Revises: 
Create Date: 2021-07-27 14:44:39.194354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151c1ec2e162'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('japTitle', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('trailer', sa.String(), nullable=False),
    sa.Column('mediumPic', sa.String(), nullable=False),
    sa.Column('largePic', sa.String(), nullable=False),
    sa.Column('extraLargePic', sa.String(), nullable=False),
    sa.Column('bannerPic', sa.String(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('episodes', sa.Integer(), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=False),
    sa.Column('ranking', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullName', sa.String(), nullable=False),
    sa.Column('mediumPic', sa.String(), nullable=True),
    sa.Column('largePic', sa.String(), nullable=True),
    sa.Column('animeId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animeId'], ['anime.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=80), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('animeId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animeId'], ['anime.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('table_anime',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'anime_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_anime')
    op.drop_table('reviews')
    op.drop_table('characters')
    op.drop_table('users')
    op.drop_table('anime')
    # ### end Alembic commands ###
