"""empty message

Revision ID: c6e61435f891
Revises: 151c1ec2e162
Create Date: 2021-07-28 08:44:50.622960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e61435f891'
down_revision = '151c1ec2e162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime', sa.Column('averageColor', sa.String(), nullable=True))
    op.alter_column('anime', 'mediumPic',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('anime', 'largePic',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('anime', 'extraLargePic',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anime', 'extraLargePic',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('anime', 'largePic',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('anime', 'mediumPic',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('anime', 'averageColor')
    # ### end Alembic commands ###
